name: volmicro
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - jupyterlab
  - ipykernel
  - requests
  - yfinance
  - polars
  - pyarrow
  - fastparquet
  - numba
  - llvmlite
  - orjson
  - python-dotenv
  - pip
  - pip:
      - ta
      - ccxt
