# configs/example.yaml
# --------------------------------------------------------
# Configuración mínima reproducible de un run.
# Cambias parámetros aquí sin tocar código.
# --------------------------------------------------------

mode: backtest

data:
  symbol: "BTCUSDT"     # par a simular
  interval: "1h"        # timeframe (1m, 5m, 1h, 4h, 1d)
  start: "2025-10-25"   # fecha inicio (YYYY-MM-DD)
  end:   "2025-10-28"   # fecha fin    (YYYY-MM-DD)

execution:
  fees_bps: 10          # comisiones (10 bps = 0.10%)
  slippage_bps: 5       # slippage simulado (5 bps = 0.05%)
  log_every: 50         # cada cuántas velas se hace log INFO (0 = solo la primera)

risk:
  position_size_usdt: 100  # tamaño fijo por orden en USDT (simple para empezar)

strategy:
  name: "sma_cross"     # nombre simbólico; usa el que tengas implementado
  params:
    fast: 10
    slow: 50

reports:
  output_dir: "reports" # carpeta para salidas (csv/json/png/etc.)
