name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project (editable) + dev deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # 1) instala el paquete y sus dependencias base (pandas, numpy, pyyaml, binance-connector)
          pip install -e .
          # 2) instala las dependencias de desarrollo (pytest, mypy, ruff, black, pre-commit)
          pip install -e ".[dev]"
          # 3) verificación defensiva (debug rápido)
          python - <<'PY'
          import importlib, sys
          for mod in ("pandas","numpy","yaml","binance"):
              try:
                  importlib.import_module(mod)
                  print(f"[CI] OK import {mod}")
              except Exception as e:
                  print(f"[CI] FAIL import {mod}: {e}", file=sys.stderr)
                  raise
          PY

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: |
          pytest -q tests/
