name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project (editable) + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      # Ejecuta los hooks definidos en .pre-commit-config.yaml
      # (Black, Ruff, Mypy, etc.). Usa la acción oficial de pre-commit.
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      # Ejecuta la batería de tests
      - name: Run tests
        run: pytest -q
