name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project (editable) + dev deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Intento principal: instalar proyecto en editable + extras dev desde pyproject.toml
          pip install -e ".[dev]" || true
          # Fallback robusto: si pytest no quedó instalado, instálalo explícitamente
          python - <<'PY'
          import shutil, sys, subprocess
          if shutil.which("pytest") is None:
              print("[CI] pytest no encontrado tras 'pip install -e .[dev]'. Instalando fallback...")
              subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest>=7.4"])
          else:
              print("[CI] pytest encontrado correctamente.")
          PY

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: pytest -q
